INFO 2024-06-21 20:38:18 _internal.py: 97]  * Restarting with watchdog (windowsapi)
DEBUG 2024-06-21 20:38:23 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-06-21 20:38:23 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-06-21 20:38:23 auth.py: 50] Trying paths: ['C:\\Users\\Hp\\.docker\\config.json', 'C:\\Users\\Hp\\.dockercfg']
DEBUG 2024-06-21 20:38:23 auth.py: 54] Found file at path: C:\Users\Hp\.docker\config.json
DEBUG 2024-06-21 20:38:23 auth.py: 242] Found 'credsStore' section
WARNING 2024-06-21 20:38:26 _internal.py: 97]  * Debugger is active!
INFO 2024-06-21 20:38:26 _internal.py: 97]  * Debugger PIN: 280-840-987
INFO 2024-06-21 20:38:27 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:38:27] "POST /upload_test HTTP/1.1" 200 -
INFO 2024-06-21 20:38:44 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:38:44] "POST /upload_test HTTP/1.1" 200 -
INFO 2024-06-21 20:39:23 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:39:23] "POST /upload_test HTTP/1.1" 200 -
INFO 2024-06-21 20:40:16 _internal.py: 97]  * Detected change in 'E:\\Aiwi\\Common\\project3\\app.py', reloading
INFO 2024-06-21 20:40:16 _internal.py: 97]  * Detected change in 'E:\\Aiwi\\Common\\project3\\app.py', reloading
INFO 2024-06-21 20:40:18 _internal.py: 97]  * Restarting with watchdog (windowsapi)
DEBUG 2024-06-21 20:40:23 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-06-21 20:40:23 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-06-21 20:40:23 auth.py: 50] Trying paths: ['C:\\Users\\Hp\\.docker\\config.json', 'C:\\Users\\Hp\\.dockercfg']
DEBUG 2024-06-21 20:40:23 auth.py: 54] Found file at path: C:\Users\Hp\.docker\config.json
DEBUG 2024-06-21 20:40:23 auth.py: 242] Found 'credsStore' section
WARNING 2024-06-21 20:40:27 _internal.py: 97]  * Debugger is active!
INFO 2024-06-21 20:40:27 _internal.py: 97]  * Debugger PIN: 280-840-987
INFO 2024-06-21 20:40:27 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:40:27] "[35m[1mPOST /upload_test HTTP/1.1[0m" 500 -
INFO 2024-06-21 20:40:27 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:40:27] "[36mGET /upload_test?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
INFO 2024-06-21 20:40:27 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:40:27] "[36mGET /upload_test?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
INFO 2024-06-21 20:40:27 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:40:27] "[36mGET /upload_test?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
INFO 2024-06-21 20:40:27 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:40:27] "[36mGET /upload_test?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
INFO 2024-06-21 20:41:38 _internal.py: 97]  * Detected change in 'E:\\Aiwi\\Common\\project3\\app.py', reloading
INFO 2024-06-21 20:41:38 _internal.py: 97]  * Detected change in 'E:\\Aiwi\\Common\\project3\\app.py', reloading
INFO 2024-06-21 20:41:39 _internal.py: 97]  * Restarting with watchdog (windowsapi)
DEBUG 2024-06-21 20:41:44 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-06-21 20:41:44 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-06-21 20:41:44 auth.py: 50] Trying paths: ['C:\\Users\\Hp\\.docker\\config.json', 'C:\\Users\\Hp\\.dockercfg']
DEBUG 2024-06-21 20:41:44 auth.py: 54] Found file at path: C:\Users\Hp\.docker\config.json
DEBUG 2024-06-21 20:41:44 auth.py: 242] Found 'credsStore' section
WARNING 2024-06-21 20:41:47 _internal.py: 97]  * Debugger is active!
INFO 2024-06-21 20:41:47 _internal.py: 97]  * Debugger PIN: 280-840-987
INFO 2024-06-21 20:43:45 _internal.py: 97]  * Detected change in 'E:\\Program Files\\Python312\\Lib\\test\\__init__.py', reloading
INFO 2024-06-21 20:43:47 _internal.py: 97]  * Restarting with watchdog (windowsapi)
DEBUG 2024-06-21 20:43:51 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-06-21 20:43:51 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-06-21 20:43:51 auth.py: 50] Trying paths: ['C:\\Users\\Hp\\.docker\\config.json', 'C:\\Users\\Hp\\.dockercfg']
DEBUG 2024-06-21 20:43:51 auth.py: 54] Found file at path: C:\Users\Hp\.docker\config.json
DEBUG 2024-06-21 20:43:51 auth.py: 242] Found 'credsStore' section
WARNING 2024-06-21 20:43:55 _internal.py: 97]  * Debugger is active!
INFO 2024-06-21 20:43:55 _internal.py: 97]  * Debugger PIN: 280-840-987
INFO 2024-06-21 20:44:03 _internal.py: 97]  * Detected change in 'E:\\Aiwi\\Common\\project3\\app.py', reloading
INFO 2024-06-21 20:44:03 _internal.py: 97]  * Detected change in 'E:\\Aiwi\\Common\\project3\\app.py', reloading
INFO 2024-06-21 20:44:05 _internal.py: 97]  * Restarting with watchdog (windowsapi)
DEBUG 2024-06-21 20:44:09 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-06-21 20:44:09 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-06-21 20:44:09 auth.py: 50] Trying paths: ['C:\\Users\\Hp\\.docker\\config.json', 'C:\\Users\\Hp\\.dockercfg']
DEBUG 2024-06-21 20:44:09 auth.py: 54] Found file at path: C:\Users\Hp\.docker\config.json
DEBUG 2024-06-21 20:44:09 auth.py: 242] Found 'credsStore' section
WARNING 2024-06-21 20:44:12 _internal.py: 97]  * Debugger is active!
INFO 2024-06-21 20:44:12 _internal.py: 97]  * Debugger PIN: 280-840-987
INFO 2024-06-21 20:44:12 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:44:12] "[35m[1mPOST /upload_test HTTP/1.1[0m" 500 -
INFO 2024-06-21 20:44:13 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:44:13] "[36mGET /upload_test?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
INFO 2024-06-21 20:44:13 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:44:13] "[36mGET /upload_test?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
INFO 2024-06-21 20:44:13 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:44:13] "[36mGET /upload_test?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
INFO 2024-06-21 20:44:13 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:44:13] "[36mGET /upload_test?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
INFO 2024-06-21 20:47:08 _internal.py: 97]  * Detected change in 'E:\\myenv\\Lib\\site-packages\\werkzeug\\user_agent.py', reloading
INFO 2024-06-21 20:47:08 _internal.py: 97]  * Detected change in 'E:\\myenv\\Lib\\site-packages\\werkzeug\\datastructures\\auth.py', reloading
INFO 2024-06-21 20:47:10 _internal.py: 97]  * Restarting with watchdog (windowsapi)
DEBUG 2024-06-21 20:47:14 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-06-21 20:47:14 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-06-21 20:47:14 auth.py: 50] Trying paths: ['C:\\Users\\Hp\\.docker\\config.json', 'C:\\Users\\Hp\\.dockercfg']
DEBUG 2024-06-21 20:47:14 auth.py: 54] Found file at path: C:\Users\Hp\.docker\config.json
DEBUG 2024-06-21 20:47:14 auth.py: 242] Found 'credsStore' section
WARNING 2024-06-21 20:47:18 _internal.py: 97]  * Debugger is active!
INFO 2024-06-21 20:47:18 _internal.py: 97]  * Debugger PIN: 280-840-987
INFO 2024-06-21 20:47:18 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:47:18] "[35m[1mPOST /upload_test HTTP/1.1[0m" 500 -
INFO 2024-06-21 20:47:18 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:47:18] "[36mGET /upload_test?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
INFO 2024-06-21 20:47:18 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:47:18] "[36mGET /upload_test?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
INFO 2024-06-21 20:47:18 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:47:18] "[36mGET /upload_test?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
INFO 2024-06-21 20:47:18 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:47:18] "[36mGET /upload_test?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
INFO 2024-06-21 20:47:40 _internal.py: 97]  * Detected change in 'E:\\Aiwi\\Common\\project3\\app.py', reloading
INFO 2024-06-21 20:47:40 _internal.py: 97]  * Detected change in 'E:\\Aiwi\\Common\\project3\\app.py', reloading
INFO 2024-06-21 20:47:42 _internal.py: 97]  * Restarting with watchdog (windowsapi)
DEBUG 2024-06-21 20:47:45 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-06-21 20:47:45 cmd.py: 1253] Popen(['git', 'version'], cwd=E:\Aiwi\Common\project3, stdin=None, shell=False, universal_newlines=False)
DEBUG 2024-06-21 20:47:46 auth.py: 50] Trying paths: ['C:\\Users\\Hp\\.docker\\config.json', 'C:\\Users\\Hp\\.dockercfg']
DEBUG 2024-06-21 20:47:46 auth.py: 54] Found file at path: C:\Users\Hp\.docker\config.json
DEBUG 2024-06-21 20:47:46 auth.py: 242] Found 'credsStore' section
WARNING 2024-06-21 20:47:49 _internal.py: 97]  * Debugger is active!
INFO 2024-06-21 20:47:49 _internal.py: 97]  * Debugger PIN: 280-840-987
INFO 2024-06-21 20:47:51 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:47:51] "POST /upload_test HTTP/1.1" 200 -
INFO 2024-06-21 20:48:05 _internal.py: 97] 127.0.0.1 - - [21/Jun/2024 20:48:05] "POST /evaluate HTTP/1.1" 200 -
